# Generated by Django 5.2 on 2025-04-20 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nameextractor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="nameextractor.company",
            ),
        ),
    ]
